// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { PingPingGetError, PingPingGetResponse, AskAskPostData, AskAskPostError, AskAskPostResponse, LayoutLayoutPostData, LayoutLayoutPostError, LayoutLayoutPostResponse, SquarifySquarifyPostData, SquarifySquarifyPostError, SquarifySquarifyPostResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Ping
 */
export const pingPingGet = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<PingPingGetResponse, PingPingGetError, ThrowOnError>({
    ...options,
    url: '/ping'
}); };

/**
 * Ask
 */
export const askAskPost = <ThrowOnError extends boolean = false>(options: Options<AskAskPostData, ThrowOnError>) => { return (options?.client ?? client).post<AskAskPostResponse, AskAskPostError, ThrowOnError>({
    ...options,
    url: '/ask'
}); };

/**
 * Layout
 */
export const layoutLayoutPost = <ThrowOnError extends boolean = false>(options: Options<LayoutLayoutPostData, ThrowOnError>) => { return (options?.client ?? client).post<LayoutLayoutPostResponse, LayoutLayoutPostError, ThrowOnError>({
    ...options,
    url: '/layout'
}); };

/**
 * Squarify
 */
export const squarifySquarifyPost = <ThrowOnError extends boolean = false>(options: Options<SquarifySquarifyPostData, ThrowOnError>) => { return (options?.client ?? client).post<SquarifySquarifyPostResponse, SquarifySquarifyPostError, ThrowOnError>({
    ...options,
    url: '/squarify'
}); };